"use client";

import { useMemo, useState } from "react";
import fixtureJson from "@/lib/fixtures/s03.json";
import type { SimulationFixture } from "@/lib/vtms-types";
import { c, flow, kw, pct } from "@/lib/format";
import { ThermalLoop } from "@/components/thermal-loop";
import { SignalChart } from "@/components/signal-chart";

const fixture = fixtureJson as unknown as SimulationFixture;

export function PlaybackWorkspace({ mode = "results" }: { mode?: "overview" | "results" | "system" }) {
  const [index, setIndex] = useState(Math.min(6, fixture.timeSeries.length - 1));
  const point = fixture.timeSeries[index];
  const maxIndex = fixture.timeSeries.length - 1;
  const balancePass = fixture.energyBalance.normalized_residual <= 0.001;
  const selected = useMemo(() => ({
    engine: c(point.engine_structure_temp_c), coolant: c(point.coolant_temp_c), radiator: kw(point.radiator_heat_w),
    pump: flow(point.pump_flow_kg_s), air: flow(point.air_flow_kg_s), thermostat: pct(point.thermostat_fraction), fan: pct(point.fan_fraction),
  }), [point]);

  if (mode === "overview") {
    return (
      <div className="overview-playback">
        <div className="section-head"><div><span className="eyebrow">CANONICAL SIMULATION PLAYBACK</span><h2>S-03 Hot Ambient Idle</h2></div><span className="fixture-badge">Frozen VTMS-V1 fixture</span></div>
        <ThermalLoop point={point} compact />
        <div className="playback-control"><span>t = {point.time_s.toFixed(0)} s</span><input aria-label="Simulation playback time" min="0" max={maxIndex} value={index} onChange={(event) => setIndex(Number(event.target.value))} type="range" /><span>{fixture.scenario.duration_s.toFixed(0)} s</span></div>
        <div className="metric-strip"><div><span>Engine</span><strong>{selected.engine}</strong></div><div><span>Coolant</span><strong>{selected.coolant}</strong></div><div><span>Radiator</span><strong>{selected.radiator}</strong></div><div><span>Pump</span><strong>{selected.pump}</strong></div></div>
      </div>
    );
  }

  if (mode === "system") {
    return (
      <div className="system-workspace">
        <div className="system-stage"><ThermalLoop point={point} /><div className="playback-control"><span>t = {point.time_s.toFixed(0)} s</span><input aria-label="Simulation playback time" min="0" max={maxIndex} value={index} onChange={(event) => setIndex(Number(event.target.value))} type="range" /><span>{fixture.scenario.duration_s.toFixed(0)} s</span></div></div>
        <aside className="component-inspector"><span className="eyebrow">SELECTED STATE</span><h3>System at {point.time_s.toFixed(0)} s</h3><dl><div><dt>Engine</dt><dd>{selected.engine}</dd></div><div><dt>Coolant</dt><dd>{selected.coolant}</dd></div><div><dt>Thermostat</dt><dd>{selected.thermostat}</dd></div><div><dt>Fan command</dt><dd>{selected.fan}</dd></div><div><dt>Radiator heat</dt><dd>{selected.radiator}</dd></div><div><dt>Air flow</dt><dd>{selected.air}</dd></div></dl><p className="muted-note">Playback uses a frozen result generated by the Python engine. It is not live telemetry.</p></aside>
      </div>
    );
  }

  return (
    <div className="results-workspace">
      <SignalChart points={fixture.timeSeries} selectedIndex={index} />
      <div className="playback-control prominent"><span>t = {point.time_s.toFixed(0)} s</span><input aria-label="Simulation playback time" min="0" max={maxIndex} value={index} onChange={(event) => setIndex(Number(event.target.value))} type="range" /><span>{fixture.scenario.duration_s.toFixed(0)} s</span></div>
      <div className="results-grid"><ThermalLoop point={point} /><div className="selected-values"><span className="eyebrow">SELECTED VALUES</span><dl><div><dt>Q engine</dt><dd>{kw(point.engine_heat_w)}</dd></div><div><dt>Q radiator</dt><dd>{selected.radiator}</dd></div><div><dt>Pump flow</dt><dd>{selected.pump}</dd></div><div><dt>Air flow</dt><dd>{selected.air}</dd></div><div><dt>Thermostat</dt><dd>{selected.thermostat}</dd></div><div><dt>Fan</dt><dd>{selected.fan}</dd></div></dl></div></div>
      <div className={balancePass ? "energy-banner pass" : "energy-banner warn"}><strong>Energy balance: {balancePass ? "PASS" : "CHECK"}</strong><span>Normalized residual {(fixture.energyBalance.normalized_residual * 100).toFixed(5)}%</span></div>
    </div>
  );
}
