import Link from "next/link";
import { PlaybackWorkspace } from "@/components/playback-workspace";
import { StatusPill } from "@/components/status-pill";

export default function OverviewPage() {
  return <>
    <section className="hero"><div className="hero-copy"><div className="hero-status"><StatusPill tone="verified">Numerical verification passing</StatusPill><StatusPill tone="pending">Controlled validation pending</StatusPill></div><span className="eyebrow">VTMS-V1 · PHYSICS-BASED AUTOMOTIVE THERMAL SIMULATION</span><h1>See where the heat goes.</h1><p>Explore transient engine and coolant behavior, thermostat and bypass flow, fan and ram airflow, radiator heat rejection, and fault response through a traceable engineering model.</p><div className="hero-actions"><Link className="button primary" href="/simulate">Open Simulation Lab</Link><Link className="button secondary" href="/validation">Review validation evidence</Link></div></div><aside className="hero-model-card"><span className="eyebrow">CURRENT MODEL</span><strong>VTMS-V1</strong><dl><div><dt>Equation set</dt><dd>EM-V1</dd></div><div><dt>States</dt><dd>2 transient</dd></div><div><dt>Solver</dt><dd>RK45</dd></div><div><dt>Radiator</dt><dd>ε-NTU</dd></div><div><dt>Tests</dt><dd>22 passing</dd></div></dl><small>Generic physics model. Not an OEM-calibrated vehicle model or digital twin.</small></aside></section>
    <PlaybackWorkspace mode="overview" />
    <section className="three-up"><article><span className="eyebrow">SIMULATE</span><h3>Change the operating condition</h3><p>Start from a frozen canonical test, then inspect the exact scenario contract that the Python engine accepts.</p><Link href="/simulate">Simulation Lab →</Link></article><article><span className="eyebrow">UNDERSTAND</span><h3>Follow energy through the loop</h3><p>See engine heat, coolant transport, thermostat split, radiator rejection, and air-side response at one selected time.</p><Link href="/system">System Explorer →</Link></article><article><span className="eyebrow">EVIDENCE</span><h3>Separate verification from validation</h3><p>Review numerical verification, independent KIT plausibility evidence, and the preregistered Argonne validation plan.</p><Link href="/validation">Validation Evidence →</Link></article></section>
  </>;
}
